# data base configuration
spring.datasource.url=jdbc:h2:mem:commerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

# JPA configuration
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-binding-errors=always

#clé secret
api.jwt.secret-key=JOjU0zYMAFavIOU26t7+2ZdJ85DKysvlii2iU3fP2AwSBo9sHg1ZusiCn9SQKmO+y+LVGUsL5n+OqGb28dJkwbrlstboBHBK3WslZhBurrYOF6mLwuTcBOaWtEeVNMQ1K1OqBNmoMnxP6BrQ2wkK1r9g38gnBBQSFXrVAgDavCmWahGa17CBam/7HQM97eYKSKU9FMtlS9sH3ceZ3o4CFO3XlGKe40TcEaAYY3PWSDTuuH9J9pdwZMMgUu+GOX+ITH8oY4xkPzdXqFdcTpNRrxDHBemSJZ5869/ZRlHt8DbHMIc4JElIDneP2IqmaSVK9hFY8gSZVmj4JXRb85Zx
api.jwt.expiration-time=86400000 # 24 heures

# RSA key pair
#rsa.private-key=classpath:keys/private.pem
#rsa.public-key=classpath:keys/public.pem